### ISSUE TITLE
goFile.UploadFileAsync Returns Null, File Continues To Upload

### ISSUE THREAD

**Issue by Jamadoo** [waffle-lord/GoFileSharp#15]
Hi, I'm trying to upload a video to my goFile account. But when I run the command "goFile.UploadFileAsync" (and await it), the code yields only until the upload is at about 3%, then returns null. No errors or warnings.

Code:
```c#
/// Upload File
// Setup
var goFile = new GoFile(new GoFileOptions
{
  ApiToken = "MY API KEY HERE",
  PreferredZone = ServerZone.Europe
});
var fileInfo = new FileInfo("MY VALID FILE PATH HERE.mp4");
// Track Progress
var uploadProgress = new Progress<double>((percent) =>
{
  botClient.EditMessageTextAsync(blablabla); // Telegram bot (edits a  message to display progress), dont worry about this
});
// Start Upload
var uploadedFile = await goFile.UploadFileAsync(fileInfo, uploadProgress, "bbd190b1-1d7d-4022-82e5-9f642a801944"); // Calling goFile.GetMyRootFolderAsync() and rootFolder.CreateFolderAsync("ContentID") always returns null, so i use this to upload the file to a folder. Probably need to open a new issue for that.

// Edit Message With Link
await botClient.EditMessageTextAsync($"{successText}\nVideo Link: {uploadedFile.Link}"); // edit telegram bot's message to give video link. I get a error here, because "uploadedFile" is null. But my telegram bot's message still get edited with new progresses (uploadProgress is still fired) and after a couple seconds the file is upload to goFile.
```

PC Specs:
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
RAM: 20GB (dont judge, my laptop has 4GB soldered)
OS: Windows 10

I am new to creating issue, so if i need to provide any other information. Just ask.

**Comment by Jamadoo** [comment]
After some debugging, I found the task gets marked as "RanToCompletion", when the await is canceled and null is returned

**Comment by Jamadoo** [comment]
Error happens inside "GoFileConstoller.UploadFileAsync". Returns error ""Unexpected character encountered while parsing value: e. Path '', line 0, position 0."". Im retrying with a new filename

**Comment by Jamadoo** [comment]
After Modifying Filename, function returns "noServer"

**Comment by Jamadoo** [comment]
All Servers Is Offline. What a convincidence. I get the error on GoFile's site as well. I'll try again in a while.

**Comment by Jamadoo** [comment]
Servers are back. Nul being returned by UploadFileAsync presists. GoFileController.UploadFileAsync works when a valid name is given. But GoFileHelper.TryGetUplaodedFile returns null.

**Comment by Jamadoo** [comment]
api.GetContentAsync response with "error-notPremium" (to get info about folder data, inside GoFileHelper.TryGetUplaodedFile). So we need premium to access the content endpoint. Indicated by the lock icon next tothe endpoint

This also explains why i cant use goFile.GetMyRootFolderAsync() and rootFolder.CreateFolderAsync("ContentID")
Would be great to note this in the readme of the lib!

![image](https://github.com/waffle-lord/GoFileSharp/assets/79752368/ffe02dc1-76f5-435d-832e-093fe6d54610)

**Comment by Jamadoo** [comment]
Using a workaround by timing the delay between the last ProgressUpdate inside the upload. When the progress's last update is longer then 5 secs, then we asume the video is uploaded.
Heres what i cameup with:

```c#
// Setup
var Options = new GoFileOptions
{
  ApiToken = "APITOKEN",
  PreferredZone = ServerZone.Europe
};
var goFile = new GoFile(Options);
var fileInfo = new FileInfo("VALID_PATH.mp4");
// Create Progress Tracker
var uploadProgress = new Progress<double>((percent) =>
{
  // Do Whatever To Display Progress
  LastUpdate = DateTime.Now.TimeOfDay;
});
// Start upload
var _api = new GoFileController();
GoFileResponse<UploadInfo> goFileResponse = await _api.UploadFileAsync(fileInfo, Options.PreferredZone, Options.ApiToken, uploadProgress);
// Check Return
if (goFileResponse.IsOK == false)
{
  Console.WriteLine($"An Error Occored While Uploading: {goFileResponse.Status}");
  return;
}
// Wait For Completion
while (DateTime.Now.TimeOfDay.Subtract(LastUpdate).TotalSeconds <= 5) await Task.Delay(1000);
//Display Folder Link
Console.Writeline(goFileResponse.Data.DownloadPage);
```

**Comment by waffle-lord** [comment]
> api.GetContentAsync response with "error-notPremium" (to get info about folder data, inside GoFileHelper.TryGetUplaodedFile). So we need premium to access the content endpoint. Indicated by the lock icon next tothe endpoint
> 
> This also explains why i cant use goFile.GetMyRootFolderAsync() and rootFolder.CreateFolderAsync("ContentID") Would be great to note this in the readme of the lib!
> 
> ![image](https://private-user-images.githubusercontent.com/79752368/322139129-ffe02dc1-76f5-435d-832e-093fe6d54610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NjEzOTUsIm5iZiI6MTcxMjk2MTA5NSwicGF0aCI6Ii83OTc1MjM2OC8zMjIxMzkxMjktZmZlMDJkYzEtNzZmNS00MzVkLTgzMmUtMDkzZmU2ZDU0NjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIyMzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYjNjNDAzMTFmZGJmNzEyZmU4NzJkNDljZGRiNzYyNzZhM2RmOTY1ZjlhYzUwYmQxMTkwZDZiNGI2ZWI3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JO5tWI129kOmXBdrkdtKK_FJW2j0Q9p4FiX69tUauMo)

This is mostly just a garbage lib I threw together to automate some things for myself (figured I'd share since I didn't see any other one available for c#), but I agree that I should add some safeguards to account for endpoints locked behind premium memberships.

I'll look into adding this in so things are more clear.

**Comment by Jamadoo** [comment]
Yea that's be great. Thanks. Just noting that some functions need premium to work in the readme.
And then also giving the syntax to the function to upload a video without
GoFileHelper.TryGetUplaodedFile (the GoFileController.UploadFile function).
That'd be enough for a avarage programmer to figure out what to do. I would
also do it for you, but tbh I have no idea how github's pull request stuff
work.

**Comment by waffle-lord** [comment]
I've added some access checks for account types and updated the readme.

I'm considering this resolved
